name: Release Mpboot Window
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        chipset_arch: ["sse4", "avx"]
        os: [windows-latest]
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Run cmake
      run: cmake . -G "MinGW Makefiles" -DIQTREE_FLAGS=${{ matrix.chipset_arch }}

    - name: Build
      run: make
    
    - uses: actions/upload-artifact@v3
      with:
        name: mpboot-${{ matrix.chipset_arch }}-${{ matrix.os }}
        path: mpboot*
