name: Release Mpboot Window
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        chipset_arch: ["avx"]
        os: [windows-latest]
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3


    - name: install tdm-gcc (v10.3.0)
      run: |
        mkdir tdm 
        cd tdm
        curl -LJ -o tdm64-gcc.exe https://github.com/jmeubank/tdm-gcc/releases/download/v10.3.0-tdm64-2/tdm64-gcc-10.3.0-2.exe
        7z e tdm64-gcc.exe
        mkdir install
        forfiles /M *.tar.xz /C "cmd /C 7z x @file -y"
        forfiles /M *.tar /C "cmd /C 7z x @file -oinstall -y"
        setx /M PATH "%PATH%;.\install\bin"

    - name: Run cmake
      run: cmake . -G "MinGW Makefiles" -DIQTREE_FLAGS=${{ matrix.chipset_arch }}

    - name: Build
      run: make
    
    - uses: actions/upload-artifact@v3
      with:
        name: mpboot-${{ matrix.chipset_arch }}-${{ matrix.os }}
        path: mpboot*
