name: Release Mpboot
on:
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        chipset_arch: ["sse4", "avx"]
        # os: [ubuntu-latest]
        os: [windows-latest]
    permissions:
      contents: write
    runs-on: ${{ matrix.os }}
    steps:
    - uses: actions/checkout@v3

    - name: Setup cmake
      uses: jwlawson/actions-setup-cmake@v1.13
      with:
        cmake-version: '3.16.x'

    - name: Run cmake
      run: cmake . -DIQTREE_FLAGS=${{ matrix.chipset_arch }} -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++

    - name: Build
      run: make
    
    - uses: actions/upload-artifact@v3
      with:
        name: mpboot-${{ matrix.chipset_arch }}-${{ matrix.os }}
        path: mpboot*
