name: Release Mpboot
on:
  workflow_dispatch:
    inputs:
      version:
        required: true
        type: string
        description: Sematic versioning

jobs:
  windows:
    permissions:
      contents: write
    uses: aqaurius6666/mpboot/.github/workflows/build-windows.yaml@mpboot
    with:
      version: ${{ inputs.version }}
  ubuntu:
    permissions:
      contents: write
    uses: aqaurius6666/mpboot/.github/workflows/build-windows.yaml@mpboot
    with:
      version: ${{ inputs.version }}